Bug fix for CleanUp
   File "/usr/lib/python2.7/dist-packages/deployerlib/commands/cleanup.py", line 47, in execute
    self.log.critical('Failed to remove {1}, because: {2}'.format(filename, res))
IndexError: tuple index out of range

Also change to non-fatal error, since we don't want automated jobs to be
marked as failed when there are problems with cleanup.